# Deploy to Kubernetes
# Build a Docker image, push to an Azure Container Registry, and deploy it to Azure Kubernetes Service.
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation - Docker Hub/ACR/...
  dockerRegistryServiceConnection: '072ddc33-8af3-499b-acb9-2bfebeb21845'
  imageRepository: 'express-aks'
  containerRegistryName: 'atulmakshelm'

  dockerfilePath: '**/Dockerfile'

  # Kubernetes Environment
  environmentName: 'expressAKS-dev'
  k8sResourceName: "smarthotel-web"
  k8sResourceNamespace: "smarthotel-web"

    # Docker Image Name
  imageName: 'express-aks'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool: default
    steps:
    - script: echo building and pushing the images to ACR

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: DeployToKubernetes
    displayName: Deploy job
    environment: expressAKS-dev.smarthotel-web
    pool: default
    strategy:
      runOnce:
        deploy:
          steps:
          - script: deploy kubernetes
              