on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: rogoyalacr.azurecr.io
        username: ${{ secrets.acr_rogoyalacr_username }}
        password: ${{ secrets.acr_rogoyalacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t rogoyalacr.azurecr.io/arsasanakubcluster:${{ github.sha }}
        docker push rogoyalacr.azurecr.io/arsasanakubcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_arsasanakubcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep arsasanakubcluster1591 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace arsasanakubcluster1591`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: arsasanakubcluster1591
        container-registry-url: rogoyalacr.azurecr.io
        container-registry-username: ${{ secrets.acr_rogoyalacr_username }}
        container-registry-password: ${{ secrets.acr_rogoyalacr_password }}
        secret-name: arsasanakubcdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: arsasanakubcluster1591
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          rogoyalacr.azurecr.io/arsasanakubcluster:${{ github.sha }}
        imagepullsecrets: |
          arsasanakubcdockerauth